/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FriendsAddRouteImport } from './routes/friends.add'
import { Route as EventNewRouteImport } from './routes/event.new'
import { Route as EventEventIdRouteImport } from './routes/event.$eventId'
import { Route as ClubsClubIdRouteImport } from './routes/clubs.$clubId'
import { Route as AdviceAdviceIdRouteImport } from './routes/advice.$adviceId'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsAddRoute = FriendsAddRouteImport.update({
  id: '/friends/add',
  path: '/friends/add',
  getParentRoute: () => rootRouteImport,
} as any)
const EventNewRoute = EventNewRouteImport.update({
  id: '/event/new',
  path: '/event/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EventEventIdRoute = EventEventIdRouteImport.update({
  id: '/event/$eventId',
  path: '/event/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsClubIdRoute = ClubsClubIdRouteImport.update({
  id: '/clubs/$clubId',
  path: '/clubs/$clubId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdviceAdviceIdRoute = AdviceAdviceIdRouteImport.update({
  id: '/advice/$adviceId',
  path: '/advice/$adviceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/discover': typeof DiscoverRoute
  '/network': typeof NetworkRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/signin': typeof SigninRoute
  '/welcome': typeof WelcomeRoute
  '/advice/$adviceId': typeof AdviceAdviceIdRoute
  '/clubs/$clubId': typeof ClubsClubIdRoute
  '/event/$eventId': typeof EventEventIdRoute
  '/event/new': typeof EventNewRoute
  '/friends/add': typeof FriendsAddRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/discover': typeof DiscoverRoute
  '/network': typeof NetworkRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/signin': typeof SigninRoute
  '/welcome': typeof WelcomeRoute
  '/advice/$adviceId': typeof AdviceAdviceIdRoute
  '/clubs/$clubId': typeof ClubsClubIdRoute
  '/event/$eventId': typeof EventEventIdRoute
  '/event/new': typeof EventNewRoute
  '/friends/add': typeof FriendsAddRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/discover': typeof DiscoverRoute
  '/network': typeof NetworkRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/signin': typeof SigninRoute
  '/welcome': typeof WelcomeRoute
  '/advice/$adviceId': typeof AdviceAdviceIdRoute
  '/clubs/$clubId': typeof ClubsClubIdRoute
  '/event/$eventId': typeof EventEventIdRoute
  '/event/new': typeof EventNewRoute
  '/friends/add': typeof FriendsAddRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/discover'
    | '/network'
    | '/notifications'
    | '/profile'
    | '/signin'
    | '/welcome'
    | '/advice/$adviceId'
    | '/clubs/$clubId'
    | '/event/$eventId'
    | '/event/new'
    | '/friends/add'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/discover'
    | '/network'
    | '/notifications'
    | '/profile'
    | '/signin'
    | '/welcome'
    | '/advice/$adviceId'
    | '/clubs/$clubId'
    | '/event/$eventId'
    | '/event/new'
    | '/friends/add'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/discover'
    | '/network'
    | '/notifications'
    | '/profile'
    | '/signin'
    | '/welcome'
    | '/advice/$adviceId'
    | '/clubs/$clubId'
    | '/event/$eventId'
    | '/event/new'
    | '/friends/add'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  DiscoverRoute: typeof DiscoverRoute
  NetworkRoute: typeof NetworkRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  SigninRoute: typeof SigninRoute
  WelcomeRoute: typeof WelcomeRoute
  AdviceAdviceIdRoute: typeof AdviceAdviceIdRoute
  ClubsClubIdRoute: typeof ClubsClubIdRoute
  EventEventIdRoute: typeof EventEventIdRoute
  EventNewRoute: typeof EventNewRoute
  FriendsAddRoute: typeof FriendsAddRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends/add': {
      id: '/friends/add'
      path: '/friends/add'
      fullPath: '/friends/add'
      preLoaderRoute: typeof FriendsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/new': {
      id: '/event/new'
      path: '/event/new'
      fullPath: '/event/new'
      preLoaderRoute: typeof EventNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$eventId': {
      id: '/event/$eventId'
      path: '/event/$eventId'
      fullPath: '/event/$eventId'
      preLoaderRoute: typeof EventEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs/$clubId': {
      id: '/clubs/$clubId'
      path: '/clubs/$clubId'
      fullPath: '/clubs/$clubId'
      preLoaderRoute: typeof ClubsClubIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advice/$adviceId': {
      id: '/advice/$adviceId'
      path: '/advice/$adviceId'
      fullPath: '/advice/$adviceId'
      preLoaderRoute: typeof AdviceAdviceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  DiscoverRoute: DiscoverRoute,
  NetworkRoute: NetworkRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  SigninRoute: SigninRoute,
  WelcomeRoute: WelcomeRoute,
  AdviceAdviceIdRoute: AdviceAdviceIdRoute,
  ClubsClubIdRoute: ClubsClubIdRoute,
  EventEventIdRoute: EventEventIdRoute,
  EventNewRoute: EventNewRoute,
  FriendsAddRoute: FriendsAddRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
